#!/usr/bin/env bash
# Bash script that install nginx
sudo apt update -y
sudo apt install nginx -y
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
