#!/usr/bin/env bash
# This script loops from 1 to 10 and prints "bad luck" for the 4th iteration, "good luck" for 8th iteration and "Holberton School" for the rest
x=0
while [ $x -lt 10 ]
do
	if [ $x = 3 ]
	then
		echo "bad luck"
	elif [ $x = 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	x=$((x + 1))
done
