#!/usr/bin/env bash
# Bash script that runs the prev task but short & sweet
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx /usr/sbin/service nginx st
